### ISSUE TITLE
Segfault on taskbar menu spawn

### ISSUE THREAD

**Issue by mobusdorphin** [bbidulock/icewm#308]
Using 1.4.2 and having an issue with a menu button on the taskbar.  The current "/home/user/.icewm/toolbar" config looks like this:

```
runonce "Prog 1" - "Class.prog" wrapper_script ARG                                                                                                      
prog Office - /path/to/libreoffice_wrapper                                                                                                            
menu "Browser" - {                                                                                                                                         
prog "Site 1"  - /path/to/wrapper arg1                                                                                               
prog "Site 2"  - /path/to/wrapper arg2                                          
prog "Site 3"  - /path/to/wrapper arg3                                                
}                                                                                                                                                          
prog Email - /path/to/thunderbird                                                                                                                 
prog PDF - /path/to/pdfviewer
```

When I take the Menu part out, and use the three sites as regular buttons, everything launches fine, but when launching the menu, instead of popping up a dialog, the wm decorations disappear, and then a window appears in the bottom right corner that cannot be closed until I restart.  

I've attached a few core dumps that are generated each time this happens.  I was able to look at the backtraces through GDB and have a vague idea of what is going on, but I'm still not proficient enough to drive it home to a solution.  

Here's a backtrace in case this is convenient:

```
#0  0x00007f7ca9053bcc in free () at /lib64/libc.so.6
#1  0x000000000046d802 in YStringArray::clear() (this=this@entry=0x7b1398) at yarray.cc:136
#2  0x00000000004427f0 in DProgram::~DProgram() (this=0x7b1398, __in_chrg=<optimized out>) at yarray.h:219
#3  0x00000000004427f0 in DProgram::~DProgram() (this=0x7b1350, __in_chrg=<optimized out>) at wmprog.cc:143
#4  0x0000000000442859 in DProgram::~DProgram() (this=0x7b1350, __in_chrg=<optimized out>) at wmprog.cc:145
#5  0x000000000044126f in DObjectMenuItem::~DObjectMenuItem() (this=0x7b0c10, __in_chrg=<optimized out>) at wmprog.cc:47
#6  0x0000000000441299 in DObjectMenuItem::~DObjectMenuItem() (this=0x7b0c10, __in_chrg=<optimized out>) at wmprog.cc:48
#7  0x0000000000459311 in YMenu::~YMenu() (this=0x7b55c8) at yarray.h:162
#8  0x0000000000459311 in YMenu::~YMenu() (this=0x7b55c8, __in_chrg=<optimized out>) at yarray.h:151
#9  0x0000000000459311 in YMenu::~YMenu() (this=0x7b54d0, __in_chrg=<optimized out>) at ymenu.cc:103
#10 0x00000000004413a6 in ObjectMenu::~ObjectMenu() (this=0x7b54d0, __in_chrg=<optimized out>) at wmprog.cc:74
#11 0x00000000004413a6 in ObjectMenu::~ObjectMenu() (this=0x7b54d0, __in_chrg=<optimized out>) at wmprog.cc:75
#12 0x000000000047c1ff in YWindow::setPosition(int, int) (this=this@entry=0x7b5640, x=<optimized out>, y=<optimized out>) at ywindow.cc:1063
#13 0x0000000000479693 in YPopupWindow::popup(YWindow*, YWindow*, YPopDownListener*, int, int, int, int, int, unsigned int) (this=0x7b5640, owner=owner@entry=0x7b5900, forWindow=forWindow@entry=0x7b5900, popDown=popDown@entry=0x0, x=<optimized out>, y=<optimized out>, x_delta=x_delta@entry=0, y_delta=28, xiScreen=0, flags=<optimized out>, flags@entry=3) at ypopup.cc:187
#14 0x000000000045f938 in YButton::popup(bool) (this=0x7b5900, mouseDown=<optimized out>) at ybutton.cc:418
#15 0x0000000000460d01 in YButton::handleButton(XButtonEvent const&) (this=0x7b5900, button=...) at ybutton.cc:278
#16 0x000000000047c8e2 in YWindow::handleEvent(_XEvent const&) (this=0x7b5900, event=...) at ywindow.cc:510
#17 0x000000000047fb1f in YXApplication::handleWindowEvent(unsigned long, _XEvent&) (this=this@entry=0x7ffe363aefb0, xwindow=<optimized out>, xev=...) at yxapp.cc:1074
#18 0x000000000047fce0 in YXApplication::handleXEvents() (this=0x7ffe363aefb0) at yxapp.cc:1029
#19 0x000000000046ca4a in YApplication::mainLoop() (this=this@entry=0x7ffe363aefb0) at yapp.cc:337
#20 0x0000000000409438 in main(int, char**) (argc=2, argv=0x7ffe363af1e8) at wmapp.cc:1565
```

Please let me know anything else I can do to help!

[icewm-1.4.2-toolbar-menu-coredumps.tar.gz](https://github.com/bbidulock/icewm/files/2484648/icewm-1.4.2-toolbar-menu-coredumps.tar.gz)

**Comment by gijsbers** [comment]
This is a known bug of 1.4.2 and was fixed in _current_ a long time ago.

**Comment by gijsbers** [comment]
@mobusdorphin See #195.

**Comment by mobusdorphin** [comment]
Thanks a bunch!
